version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:17.4-alpine3.21
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mydb
      PGDATA: /data/postgresql
    volumes:
      - ./data/pg:/data/postgresql
    networks:
      - one_network
  brain-agriculture-api:
    build:
      context: .
    container_name: brain-agriculture-api
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    networks:
      - one_network
    environment:
      DATABASE_URL: postgresql://postgres:docker@postgres:5432/mydb?schema=public
  
networks:
  one_network:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: ./data/pg
      o: bind